---
- src: geerlingguy.composer
- src: geerlingguy.git
- src: geerlingguy.redis
- src: geerlingguy.mysql
- src: geerlingguy.nginx
- src: geerlingguy.nodejs
- src: geerlingguy.php
- src: geerlingguy.php-mysql
- src: geerlingguy.swap